[
build
]

    publish = "."
    command = "npx tailwinds -i styles/main.css -o styles/mainout.css"

[[
headers
]]
    for = "/styles/*"
    [
headers.values
]
    Cache-Control = "public, max-age=0, must-revalidate"