[build]
  publish = "."
  command = "npx tailwindcss -i styles/main.css -o styles/mainout.css"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"